/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_vespa_model_application_validation_NativeVerifyRankSetup */

#ifndef _Included_com_yahoo_vespa_model_application_validation_NativeVerifyRankSetup
#define _Included_com_yahoo_vespa_model_application_validation_NativeVerifyRankSetup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_vespa_model_application_validation_NativeVerifyRankSetup
 * Method:    verify
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yahoo_vespa_model_application_validation_NativeVerifyRankSetup_verify
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
